apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pandeyysatyam/argocd-in-one-shot.git
    targetRevision: main
    path: 04_first_app_deployment/declarative_approach/online_shop

  destination:
    server: https://192.168.242.46:33893
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
